version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true
    networks:
      - network

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    networks:
      - network

  celery:
    build: .
    command: celery -A celery_queue.create_celery worker --loglevel=info
    depends_on:
      - redis
      - postgres
    restart: unless-stopped
    networks:
      - network

  celery_beat:
    build: .
    command: celery -A celery_queue.create_celery beat --loglevel=info
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    networks:
      - network


volumes:
  pgdata:
    driver: local

networks:
  network:
    driver: bridge
