version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true
#    networks:
#      - network

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
#    networks:
#      - network

#  celery:
#    build: .
#    container_name: celery
#    command: ["celery", "-A celery_queue.create_celery worker -l info"]
#    depends_on:
#      - redis
#      - postgres
#    networks:
#      - network
#
#  celery_beat:
#    build: .
#    container_name: celery_beat
#    command: ["celery", "-A celery_queue.create_celery beat -l info"]
#    depends_on:
#      - postgres
#      - redis
#    networks:
#      - network


volumes:
  pgdata:
    driver: local

#networks:
#  network:
#    driver: bridge
